SERVICE_NAME=$1
PATH_TO_DOCKERFILE=$2

echo \> docker build -t webber1580/$SERVICE_NAME:$CI_PIPELINE_ID $PATH_TO_DOCKERFILE
docker build -t webber1580/$SERVICE_NAME:$CI_PIPELINE_ID $PATH_TO_DOCKERFILE